### ISSUE TITLE
[Suggestion] Highlight `n` lines surrounding (before and after) the one with focus.

### ISSUE THREAD

**Issue by battaglr** [davidleghorn/atom-focus-mode#1]
First at all, awesome work!

The focus mode didn't worked as I assumed —nothing wrong with that, obviously; I was expecting that the lines surrounding the one with focus also get highlighted —maybe not 100%, but not as faded as the rest.

Maybe this could be added as an extra mode. What do you think?

**Comment by davidleghorn** [comment]
Hi, thanks for your comment. I like the idea, I think perhaps a configuration option for the single line focus mode where you can optionally choose to highlight x number of lines around the focussed line could be a nice option, or as you say add the feature as a new mode.

**Comment by battaglr** [comment]
I like the idea of a config for the single line mode. :+1:

**Comment by davidleghorn** [comment]
Hi, I have added your feature suggestion in the 0.2.0 release as a new mode named "focus shadow mode" (ctrl+alt+u). The 3 lines above and below the cursor line are highlighted with 60% opacity. Will add a configuration option so you can configure the number of lines in the next release.

**Comment by battaglr** [comment]
Great work, mate! It's looking and working perfect!

Thanks for taking up the suggestion. 😉

P.S.: I consider this issue as closed, but that's your call.

**Comment by davidleghorn** [comment]
Thanks :)
