### ISSUE TITLE
Use the selector `atom-panel` instead of the `tool-panel` class.

### ISSUE THREAD

**Issue by kkalkhoff** [davidleghorn/atom-focus-mode#3]
In styles/focus-mode.less: Use the selector `atom-panel` instead of the `tool-panel` class.

**Comment by davidleghorn** [comment]
Hi Czahoo, thanks for the suggestion. That would be a neat way to apply focus mode reduced opacity to all atom panels. For the moment I only want to apply focus mode reduced opacity to the tool panel. There are some atom panels like the find/replace panel that I don't want focus mode to style as I want them to retain their normal 100% opacity.
