### ISSUE TITLE
Deprecated selector in `atom-focus-mode\styles\focus-mode.less`

### ISSUE THREAD

**Issue by KnickerPicker** [davidleghorn/atom-focus-mode#4]
In `atom-focus-mode\styles\focus-mode.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.focus-mode atom-text-editor::shadow .line` => `.focus-mode atom-text-editor.editor .line`

* `.focus-mode atom-text-editor::shadow .line .comment,
.focus-mode atom-text-editor::shadow .line.cursor-line,
.focus-mode atom-text-editor::shadow .focus-line` => `.focus-mode atom-text-editor.editor .line .syntax--comment,
.focus-mode atom-text-editor.editor .line.cursor-line,
.focus-mode atom-text-editor.editor .focus-line`

* `.focus-mode.line-55 atom-text-editor::shadow .focus-line` => `.focus-mode.line-55 atom-text-editor.editor .focus-line`

* `.focus-mode.line-55 atom-text-editor::shadow .line .comment,
.focus-mode.line-55 atom-text-editor::shadow .line.cursor-line` => `.focus-mode.line-55 atom-text-editor.editor .line .syntax--comment,
.focus-mode.line-55 atom-text-editor.editor .line.cursor-line`

* `.focus-mode-shadow atom-text-editor::shadow .line` => `.focus-mode-shadow atom-text-editor.editor .line`

* `.focus-mode-shadow atom-text-editor::shadow .line.cursor-line,
.focus-mode-shadow atom-text-editor::shadow .line.comment.cursor-line,
.focus-mode-shadow atom-text-editor::shadow .focus-line.cursor-line` => `.focus-mode-shadow atom-text-editor.editor .line.cursor-line,
.focus-mode-shadow atom-text-editor.editor .line.syntax--comment.cursor-line,
.focus-mode-shadow atom-text-editor.editor .focus-line.cursor-line`

* `.focus-mode-shadow atom-text-editor::shadow .line.comment,
.focus-mode-shadow atom-text-editor::shadow .focus-line` => `.focus-mode-shadow atom-text-editor.editor .line.syntax--comment,
.focus-mode-shadow atom-text-editor.editor .focus-line`

* `.focus-mode atom-text-editor::shadow .line-number,
.focus-mode-shadow atom-text-editor::shadow .line-number` => `.focus-mode atom-text-editor.editor .line-number,
.focus-mode-shadow atom-text-editor.editor .line-number`

* `.focus-mode atom-text-editor::shadow .line-number.cursor-line,
.focus-mode-shadow atom-text-editor::shadow .line-number.cursor-line` => `.focus-mode atom-text-editor.editor .line-number.cursor-line,
.focus-mode-shadow atom-text-editor.editor .line-number.cursor-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by davidleghorn** [comment]
Thanks for the heads up! 
Selectors upgraded in focus mode release 0.7.0.
