### ISSUE TITLE
Doesn't auto-focus contexts

### ISSUE THREAD

**Issue by ProLoser** [davidleghorn/atom-focus-mode#5]
From the screenshot, I was under the impression that the entire heirarchy of the file would be autofocused. If I focus a line, the containing scope (loop), method, class, package (etc) would all be automatically focused but it seems there's only a history focus or fuzzy focus around the cursor.

**Comment by davidleghorn** [comment]
It doesn't focus the containing scope at the moment, but that is on my to do list. At the moment it focusses any lines that have received cursor focus, lines that have been highlighted using the mouse or a fuzzy focus around the cursor.

**Comment by davidleghorn** [comment]
Scope focus feature added in release 0.8.0 - automatically focuses lines inside the method/function/class scope that the cursor was placed inside. Implemented for js, coffee and python files - more file types to follow.
