### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Swizz** [davidleghorn/atom-focus-mode#7]
Hi there !

I am pretty in love with the idea. But, think it could be enhanced in is architecture.
You seem parsing the syntax by your self, but you missed the point that the Atom syntaxer do a lot of stuff for you (For all language ! By plugins !).

So, for the scope mode, it could be more easy to find the 
```css
.syntax--function
```
where the crusor is in.

**Comment by davidleghorn** [comment]
Hello,

Thanks for your comment. I agree it could be enhanced to use syntax info from atom.

In theory finding the “.syntax—function” class would be a good way to do it, but it’s not that simple as focus mode uses the editor’s text buffer and not the editor DOM.

I discovered after completing the regex parser solution that syntax information can be accessed from the buffer via ScopeDescriptors.

Will likely enhance the implementation to use syntax info from the ScopeDescriptors as it will make scope mode easier to extend for different languages.

**Comment by davidleghorn** [comment]
Added to back log
