### ISSUE TITLE
Odd shadow behavior on word-wrapped lines

### ISSUE THREAD

**Issue by jykong** [davidleghorn/atom-focus-mode#9]
In shadow focus mode, the word-wrapped lines exhibit an odd shadow behavior where the lines prior to the latest word-wrap get faded darker than all the other lines. I set the before and after lines to highlight to 10. The screenshot explains this better than I can.

![screen shot 2018-01-28 at 12 53 46 pm](https://user-images.githubusercontent.com/730394/35485228-888ee52c-042a-11e8-82a2-24a1eb620fda.png)

**Comment by davidleghorn** [comment]
Hi James, thanks for raising this and for the helpful screenshot. I have managed to re-create the bug and will try and get a fix in soon.

**Comment by davidleghorn** [comment]
Fixed in 0.12.1 release

**Comment by jykong** [comment]
Thanks for the quick fix, David! I tried the patch out and it's working
great. The last version convinced me to make the switch to using your
plugin over Zen Mode. Cheers!

**Comment by davidleghorn** [comment]
Cheers :)
